sudo: false
language: java
jdk:
- oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

matrix:
  include:
  - env: IDEA_VERSION="IU-182.2757.3" PHP_PLUGIN_VERSION="182.2574.13" SYMFONY_PLUGIN_VERSION="0.16.165" TOOLBOX_PLUGIN_VERSION="0.4.6" TWIG_PLUGIN_VERSION="182.3208.33" ANNOTATION_PLUGIN_VERSION="5.3" PSI_VIEWER_PLUGIN_VERSION="182.2757.2" DEPLOY=true
  - env: IDEA_VERSION="IU-2018.1.5" PHP_PLUGIN_VERSION="181.5281.35" SYMFONY_PLUGIN_VERSION="0.16.165" TOOLBOX_PLUGIN_VERSION="0.4.6" TWIG_PLUGIN_VERSION="181.3741.23" ANNOTATION_PLUGIN_VERSION="5.3" PSI_VIEWER_PLUGIN_VERSION="2018.1.2" DEPLOY=true
#  allow_failures:
#  - env: IDEA_VERSION="IU-173.4127.17" PHP_PLUGIN_VERSION="173.4127.13"

before_install:
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
- "export ORG_GRADLE_PROJECT_ideaType=${IDEA_TYPE}"
- "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_symfonyPluginVersion=${SYMFONY_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_toolboxPluginVersion=${TOOLBOX_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_twigPluginVersion=${TWIG_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_psiViewerPluginVersion=${PSI_VIEWER_PLUGIN_VERSION}"
- java -version

script:
- "./gradlew check"
- "./gradlew buildPlugin"
