sudo: false
language: java
jdk:
  - oraclejdk8
  
script: "./travis.sh"
cache:
  directories:
    - .cache
before_script:
 - chmod +x travis.sh

env:
  - PHPSTORM_ENV=2016.1
  - PHPSTORM_ENV=2016.1.2
  - PHPSTORM_ENV=2016.2
  - PHPSTORM_ENV=2016.2.1
  - PHPSTORM_ENV=eap

matrix:
  allow_failures:
    - env: PHPSTORM_ENV=eap