sudo: false
language: java
jdk:
- oraclejdk11

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

matrix:
  include:
  - env: IDEA_VERSION="IU-2020.3.1" PHP_PLUGIN_VERSION="203.6682.137" SYMFONY_PLUGIN_VERSION="0.18.179" TOOLBOX_PLUGIN_VERSION="0.4.6" TWIG_PLUGIN_VERSION="203.6682.75" ANNOTATION_PLUGIN_VERSION="5.3"

before_install:
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
- "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_symfonyPluginVersion=${SYMFONY_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_annotationPluginVersion=${ANNOTATION_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_toolboxPluginVersion=${TOOLBOX_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_twigPluginVersion=${TWIG_PLUGIN_VERSION}"
- java -version

script:
- "./gradlew check"
- "./gradlew buildPlugin"
